#!/bin/bash

# ID du commit que vous souhaitez modifier
COMMIT_ID="a722ad2bfba66f046b602f99358d537a694b9906"

# Nouvelle heure pour le commit (au format YYYY-MM-DD HH:MM:SS)
NEW_COMMIT_TIME="2023-05-22 12:00:00"

# Récupérez l'ancienne heure de commit
OLD_COMMIT_TIME=$(git log --format=%ai -n 1 $COMMIT_ID)

# Modifiez l'heure du système pour la nouvelle heure de commit
sudo date -s "$NEW_COMMIT_TIME"

# Effectuez un nouveau commit avec la même message et les mêmes modifications que le commit d'origine
git commit --amend --no-edit

# Rétablissez l'heure du système à l'heure précédente
sudo date -s "$OLD_COMMIT_TIME"

# Poussez les modifications vers la branche distante
git push --force
