#!/bin/bash

echo "Downloading necessary Python libraries..."

# Data Analysis Libraries
pip install numpy pandas matplotlib seaborn scipy plotly bokeh geopandas descartes folium

# Data Science Libraries
pip install scikit-learn statsmodels tensorflow keras jupyterlab pandas-profiling xgboost lightgbm

# Trading Libraries
pip install backtrader pyalgotrade quantlib ta-lib pyfolio zipline Backtesting
# Crypto Libraries
pip install ccxt cryptocompare pycoingecko pybithumb

# Web Scraping Libraries
pip install beautifulsoup4 scrapy requests

# Data Cleaning and Modeling Libraries
pip install pandas-datareader category_encoders featuretools imbalanced-learn mlxtend

# Data Presentation and Visualization Libraries
pip install dash dash-core-components dash-html-components dash-bootstrap-components plotly-express

# Web Development Libraries
pip install flask django fastapi

echo "All necessary Python libraries have been downloaded."

